### PR TITLE
feat: support separate viceroy install

### PR DESCRIPTION
**Pull request by Integralist**

### CODE REVIEW

**Comment by Integralist** [comment]
Need to add some workarounds for the lack of Viceroy's ARM support

**Comment by JakeChampion** [comment]
> Need to add some workarounds for the lack of Viceroy's ARM support

Viceroy supports ARM - there are darwin and linnux arm builds in the release assets -- https://github.com/fastly/Viceroy/releases/tag/v0.9.4

**Comment by Integralist** [comment]
@JakeChampion ...and Windows 😉

**Review by kailan — APPROVED** [review]
Looks great, thank you for adding the release documentation also.

**Pull request merged**
