### PR TITLE
Support CLI's `--non-interactive` option

### PR DESCRIPTION
**Pull request by Integralist**

### CODE REVIEW

**Comment by kailan** [comment]
I'm wondering if rather than this being an option, we should just pass it in to all commands? Can you think of a scenario in which you would want interactive prompts when running in GitHub Actions? @Integralist

**Comment by Integralist** [comment]
That's fair actually @kailan I think I was being overly cautious. I'll update 👍🏻

**Comment by Integralist** [comment]
@kailan ok made changes

**Review by kailan — APPROVED** [review]

**Comment by kailan** [comment]
I'll ship this with the Node 18 update tomorrow

**Pull request merged**
